#
# Generated by generate.py 
#
class CompilerInfo:
  def getWordList(self):
    return ["[break]",";","!","[br]","[br.zero]","[farcall]","[literal.s]","[literal]","[nop]","[stackreset]","@","+",">r","2/","cursor!","keyboard@","nand","page!","page@","r>","screen!"]
  def getCoreAddress(self):
    return 0x8000
  def getLoadAddress(self):
    return 0x6000
  def getBinarySize(self):
    return 0x0000
