#
# Generated by generate.py 
#
class CoreWords:
  def getWordList(self):
    return ["[halt]","@","c@","!","c!","f@","f!","page!",">r","r>",";","[r>]","[farcall]","[nop]","[lit]","[bzero]","+","nand","2/","0=","[sysinfo]","cursor!","screen!","keyboard@","block@","[stackreset]","block!"]
