#
# Generated by generate.py 
#
class CompilerInfo:
  def getWordList(self):
    return [";","!","[brzero]","[farcall]","[literal]","[nop]","[stackreset]","@","+",">r","2/","cursor!","keyboard@","nand","page!","r>","screen!"]
  def getCoreAddress(self):
    return 0x8000
  def getLoadAddress(self):
    return 0x6000
  def getBinarySize(self):
    return 0x0000
