#
# Generated by generate.py 
#
class CoreWords:
  def getWordList(self):
    return [";","!","?","[br.zero]","[br.pos]","[br]","[clr.ds]","[clr.rs]","[halt]","[literal]","[nop]","[r>]","[sysinfo]","@","+",">r","2/","c!","c@","cursor!","keyboard@","nand","page!","r>","screen!"]
